app/models/category.rb
app/models/daily_target.rb
app/models/item.rb
app/models/item_category.rb
app/models/order.rb
app/models/order_item.rb
app/models/seller.rb
app/models/user.rb
db/migrate/20200730234602_create_sellers.rb
db/migrate/20200730234645_create_categories.rb
db/migrate/20200730235410_create_orders.rb
db/migrate/20200730235517_create_items.rb
db/migrate/20200730235801_create_item_categories.rb
db/migrate/20200730235912_create_order_items.rb
db/migrate/20200731000022_create_daily_targets.rb
db/schema.rb
test/models/category_test.rb
test/models/daily_target_test.rb
test/models/item_category_test.rb
test/models/item_test.rb
test/models/order_item_test.rb
test/models/order_test.rb
test/models/seller_test.rb

- Created all models
- Through associations are remaining

Created all models and added main associations

---

app/models/item.rb
app/models/order.rb

Agregado enum en models:
```
order.rb
enum origin: [:pending, :finished]
item.rb
enum origin: [:user, :seller, :database]
```

added enum in models

---

db/migrate/20200801142143_change_items_origin.rb
db/migrate/20200801142157_change_orders_status.rb
db/schema.rb

migraciones para que funcionen los enums

Change string to integer for enums

---

app/models/order.rb
db/seeds.rb

Agregado:
- arrays de hashes ```CATEGORIES_INFO```, ```SELLERS_INFO```, ```ITEMS_INFO``` y ```NAMES_INFO``` que se pueden expandir para expandir el seed.
- simbolo ```categories_keywords:``` en ```ITEMS_INFO``` donde se agregan palabras clave de categorias de las comidas que se quieran agregar al seed.
-El resto no deberia ser necesario tocar para expandir el seed.

added seed structure

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20200801144133_add_column_in_user.rb
db/migrate/20200801185144_add_avatar_column_in_user.rb
db/migrate/20200801190447_create_active_storage_tables.active_storage.rb
db/schema.rb

Agregado:
- first_name, last_name, photo en user new y edit

User registration touch up

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss

Added green button component.

---

app/assets/stylesheets/components/_categories.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_item_cards.scss
app/assets/stylesheets/components/_item_modal.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_item_index.scss
app/javascript/components/modal_functions.js
app/javascript/packs/application.js
app/views/items/_item-card.html.erb
app/views/items/_item-modal.html.erb
app/views/items/index.html.erb
config/application.rb

Pull request por fixes en responsivenes de index, cards y navbar.
tambien ya hay mejoras para los modales

Item modal in index

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_item_modal.scss
app/controllers/order_items_controller.rb
app/policies/order_item_policy.rb
app/views/items/_item-modal.html.erb
test/policies/order_item_policy_test.rb

Base layout for model with Lucho changes done

---

app/controllers/items_controller.rb

Fixed problems with nil items and refectored date comparison

Fix bugs in items controller

---

app/controllers/orders_controller.rb
app/models/order.rb
app/policies/order_policy.rb
app/views/orders/show.html.erb
config/routes.rb
db/seeds.rb

Agregado:
- Vista de order confirmada

Order confirmada

---

app/controllers/daily_targets_controller.rb
app/controllers/items_controller.rb
app/models/user.rb

Refactored code and redistributed several methods.

Index filter | Refactored code

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cart_modal.scss
app/assets/stylesheets/components/_dropdown.scss
app/assets/stylesheets/components/_index.scss
app/views/items/_cart-modal.html.erb

- Added buttons to modify quantity
- Added drop down list to select payment method

Order view | Added buttons and drop down list

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_item_edit.scss
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb

Agregado en partial _form.html.erb:
- range_field para macros
- opciones basicas en date_field para solo habilitar 15 dias
- bootstrap basico con responsiveness row/col

Front registro mi consumo

---

app/models/user.rb

Commented 2 redundant methods: orders and daily_targets

Commented redundant methods in user model

---

app/controllers/daily_targets_controller.rb
app/controllers/items_controller.rb

Agregado:
- Resuelto bug con order status::pending. 
Agregue status:finished a los queries de order en daily_targets.controller.rb (l52, 64, 76, 88) y items_controller.rb (l109, 121, 133, 145)

Bug dailytarget consumedat nil

---

app/views/items/_form.html.erb

- Updated card title
- Updated nutrient limits

Update card were users register their consumes

---

app/assets/stylesheets/components/_item_cards.scss
app/views/items/_item-card.html.erb
app/views/items/index.html.erb

- Setted 4px padding for card-info
- Added 4px border radius
- Changed calorias tag color to green
- Deleted (commented) card shadow
- Changed card color to a stronger grey

Items index - Worked in frontend

---

app/assets/stylesheets/components/_item_modal.scss
app/views/items/_item-modal.html.erb

Applied general style changes.

Items show card - Worked in frontend

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_range.scss
app/views/items/_form.html.erb

- Set roboto font for numbers
- Improved ranges functionality so numbers change while we move the ball

Item new - Improved range functionality

---

app/views/daily_targets/show.html.erb
app/views/shared/_navbar.html.erb

Cambios:
- btn hamburguesa en vez de avatar cuando no hay foto cargada
- Carrito y btn hamburguesa de igual tamano
- Cambio texto cuando no hay consumo externo registrado a "Sin Consumo Registrado"
- btn hamburguesa solo sale en la vista items#index. Queda ver si queremos verlo en la vista de categorias cuando de haga el merge de esa branch

Carrito btn avatar btn

---

app/assets/stylesheets/components/_categories.scss
app/views/items/index.html.erb

- Used boxes with 8px padding for cards
- Setted light grey borders for cards
- Commented white arroys as are visible when the carousel moves

Alternative for categories carousel

---

app/javascript/components/increment_buttons.js
app/views/items/_item-modal.html.erb

bug where inc-dec buttons didint change the total fixed

bug where inc-dec buttons didint change the total fixed

---

app/assets/stylesheets/components/_cart_modal.scss
app/views/items/_cart-modal.html.erb
app/views/orders/show.html.erb

- Added form for address
- Made general changes in style

Added address input in my_order view

---

app/assets/stylesheets/pages/_item_edit.scss
app/views/items/_form.html.erb

- Added modal header
- Added "¿Qué comiste" placeholder
- Changed ranges color from green to grey

Item new - Worked in frontend

---

app/views/daily_targets/show.html.erb

Edited titles, nutrients bars, added cards for daily consumes, and some other general style changes.

Daily Targets - Improved general view style

---

app/assets/stylesheets/components/_checkbox.scss
app/views/items/_item-modal.html.erb
app/views/shared/_navbar.html.erb

- Changed checkbox background and border colors
- Changed checkbox tag -> ¡Lo voy a comer ahora!"

Items show - Edited checkbox colors and tag

---

app/controllers/items_controller.rb
app/views/items/index.html.erb

Se agregaron los mensajes acordes al filtro, si se eligió categoria, si se llego al limite, o si no hay opciones.
Se agrego la opcion de mostrar items sin filtro luego de avisar el estado de los objetivos

Dinamic messages for categories and target accomplished

---

app/assets/stylesheets/components/_item_cards.scss
app/assets/stylesheets/components/_item_modal.scss
app/controllers/items_controller.rb
app/views/items/_item-card.html.erb
app/views/items/_item-modal.html.erb
db/migrate/20200828205916_add_rating_to_items.rb
db/schema.rb
db/seeds.rb
db/seeds/items.rb

Se agrego rating a item
se implemento en el seed
se implemento en las views
se implemento en los controllers
se mejoro la visual de el rating en las cards 
se mejoro en el modal el alto de la descripcion

Add rating to item

---

app/views/items/index.html.erb

- Used capitalize instead of upcase
- Incremented font size to 20px

Categories card labels - Edited style

---

app/assets/stylesheets/components/_dropdown.scss
app/views/shared/_navbar.html.erb

- Setted Roboto font for labels
- Added font awesome icons

Edited navbar dropdown

---

app/views/items/_form.html.erb

- Reduced limits for calories, proteins, fats and carbs

Item new - Edited nutrients limits

---

app/assets/stylesheets/components/_navbar.scss
app/models/user.rb
app/views/shared/_navbar.html.erb

fixed negative numbers bug for the target navbar
changed to consumed/total for the target navbar
font to 14px
dinamic centering ignoring cart done

Navbar target fixes and improvements

---

app/views/daily_targets/_form.html.erb
app/views/items/_form.html.erb

Cambiado gr a g en vista de item#edit cuando el item fue comprado en la app

Cambiar gr por g

---

app/views/items/index.html.erb
app/views/shared/_footer-btn-consume.html.erb

- Added fontawesome icon
- Changed colors (background green and fonts in white)

Edited footer button (Cargar consumo)

---

app/views/daily_targets/show.html.erb

- Deleted tags inside bars
- Changed title that appears when there isn't any consume

Daily Targets - Worked in frontend

---

app/views/daily_targets/show.html.erb

Cambios:
- ```Font-size:0px```
- Amarillo y verde invertidos en las barras de daily_targets#show

Macronutrientes restantes size 0
